name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rachitsharma300
          base: header, activity, community, repositories, metadata
          theme: radical
