name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: rachitsharma300
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, lines

          plugin_achievements: yes
          plugin_achievements_display: compact

          plugin_stargazers: yes
